35_users_and_auth/some_shop/shop/urls.py
from django.urls import path
from .views import (ShopIndexView,
                    CategoriesWithProductsTree,
                    ProductsView,
                    OrdersListView,
                    get_task_info,
                    CategoriesListView,
                    CategoryCreateView,
                    CategoryDetailView,
                    CategoryUpdateView,
                    CategoryDeleteView,
                    )
app_name = "shop"
urlpatterns = [
    path("", ShopIndexView.as_view(), name="shop"),
    path("products/", ProductsView.as_view(), name="products"),
    path("categories/", CategoriesListView.as_view(), name="categories"),
    path("categories/create/", CategoryCreateView.as_view(), name="create-category"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="update-category"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category"),
    path("categories/<int:pk>/confirm-delete/", CategoryDeleteView.as_view(), name="confirm-delete-category"),
    path("orders/", OrdersListView.as_view(), name="orders"),
    path("orders/task/<task_id>/", get_task_info, name="get-order-task"),
    path("categories-tree/", CategoriesWithProductsTree.as_view(), name="categories_with_products_tree")
]

35_users_and_auth/some_shop/site_auth/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import LoginView, LogoutView, RegisterView

app_name = "site_auth"
urlpatterns = [
    # path("login/", TemplateView.as_view(template_name='site_auth/login.html'), name="login",),
    path("login/", LoginView.as_view(), name="login",),
    path("logout/", LogoutView.as_view(), name="logout",),
    path("register/", RegisterView.as_view(), name="register",),
    path("me/", TemplateView.as_view(template_name="site_auth/me.html"), name="about-me"),
]

35_users_and_auth/some_shop/some_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", TemplateView.as_view(template_name='index.html')),
    path('shop/', include('shop.urls')),
    path('auth/', include("site_auth.urls")),


]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

35_users_and_auth/some_shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        Base
        {% endblock %}

    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
<nav class="mb-2 px-3 navbar navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'shop:shop' %}">Shop</a>

    <div>
    {% if user.is_authenticated %}
        <a href="{% url 'site_auth:about-me' %}">{{ user.username }}</a>
        <a href="{% url 'site_auth:logout' %}">Logout</a>
        {% else %}
            <a class="btn btn-outline-primary" href="{% url 'site_auth:login' %}">login</a>
    {% endif %}
    </div>
 </nav>
 <div class="container">
        {% block body %}
    {% endblock %}
 </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

35_users_and_auth/some_shop/templates/index.html
{% extends 'base.html' %}

{% block title %}
Sales shop home page
{% endblock %}

{% block body %}
<h1>Welcome to home page</h1>
    <div>
        <p>Links:</p>
        <ul>
            <li>
                <a href="{% url 'shop:shop' %}">Shop page</a>
            </li>
        </ul>
    </div>

{% endblock %}